config/routes.rb
Kvazars::Application.routes.draw do

  root 'game#index'

  get 'signout' => "game#signout"
  get 'signup' => "game#signup"
  get 'signin'  => "game#signin"

  namespace :game do
    
    
    get 'building/:planet_id/build/:building_type', to: 'building#build', as: 'build_planet_building'
    get 'building/:planet_id/list', to: 'building#list', as: 'building_list'
    
    get 'technology/:technology_type/build', to: 'technology#build', as: 'build_technology'
    get 'technology/list', to: 'technology#list', as: 'technology_list'
    
    get 'planet/:planet_id/buildings' => 'building#list'
    get 'planet/index', to: 'planet#index', as: 'planets_index'
    get 'planet/:planet_id/show', to: 'planet#show', as: 'planet_show'

    get 'ship/:planet_id/list', to: 'ship#list', as: 'ship_list'
    get 'ship/:planet_id/build/:ship_type', to: 'ship#build', as: 'build_ship'

      
  end
  

  

     namespace :admin do
       resources :users
     end
end

app/models/admin/user.rb
class Admin::User < User

end

app/models/concerns/user/associations.rb
module User::Associations
  extend ActiveSupport::Concern

  included do
    has_many :planets, :dependent => :destroy
  end


end

app/models/concerns/user/planets.rb
module User::Planets
 extend ActiveSupport::Concern 

  included do |klass|
    after_create :assign_planet
  end

  private

  def assign_planet
	planet = Managers::PlanetManager.retrieve_entity_for(self)
	planet.try(:save!) if planet.new_record?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include User::Associations
  include User::Planets

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new

    AccessManager.can_call?(:extend!, Managers::BuildingManager.retrieve_entity_for(@admin_user))
    
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit!
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :login %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing admin_users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.login %></td>
        <td><%= link_to 'Show', admin_user %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
        <td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New admin_user</h1>

    <div class="notice"><%= NotificationCollector.get_errors %></div>


<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>